# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/meu_banco
spring.datasource.username=postgres
spring.datasource.password=minhasenha
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET:chave-local-desenvolvimento}

server.port=8080
springdoc.swagger-ui.path=/swagger-ui.html


# nunca commitar valores reais — usar variáveis de ambiente - lembrar de tirar depois
# Valores diretos, sem buscar de variáveis de ambiente
admin.email=admin@hotmail.com
admin.senha=coti@password